### PR TITLE
Copybara/push 2d5727eb 19a1 4386 aebc f309fb54f2de

### PR DESCRIPTION
**Pull request by jiridanek**

### CODE REVIEW

**Comment by rkubis** [comment]
What a big merge request :D

**Comment by jiridanek** [comment]
I did not do any changes. This is what's running in internal CI. There is fixed branch that Dominik created, but that is hopelessly out of date at this point. The advantage of doing it this way (Copybara, one of the options in https://github.com/rh-messaging/cli-cpp/issues/1) is that it is easy to keep internal and external versions in sync. (When I resolve the GH auth, it can even run automatically in CI.)

**Comment by rkubis** [comment]
OK, we can try to merge everything what we want and then wait for the result.

**Comment by rkubis** [comment]
Not sure how to deal with internal _commit_ messages etc.

**Comment by jiridanek** [comment]
Internal commit messages. That is easy, push everything in single squashed commit, without commit message, or tell copybara to override it with blank commit message... Is there anything worrying in the commit messages? My initial solution was to just push it, nobody cares anyways, and there is nothing truly secret in the commit messages. Maybe irrelevant (such as internal Jira numbers) but not secret)

I realized I probably want to move the files out of dtests/node_data... though. The cpp directory should be root of this repo.

**Comment by jiridanek** [comment]
New PR, for the changed paths. https://github.com/rh-messaging/cli-cpp/pull/6

**Pull request closed without merging**
